/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HBproj24.working.with.custum.generator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
